### ISSUE TITLE
True Colors values

### ISSUE THREAD

**Issue by KhalilSelyan** [ixmilia/dxf-rs#61]
Is there any plans to add access to the color value itself instead of the ACI which sometimes is not the exact color that is chosen in RGB ?

**Comment by brettfo** [comment]
True color is supported as a separate field, if written.  For a drawing R2004 or greater, this is a `i32` value on the common entity properties, e.g.,

``` rust
let my_entity = drawing.entities()....; // get the entity
let true_color = my_entity.common.color_24_bit; // i32 with the true color
```

Note that the field _must_ be present in the DXF file, otherwise it defaults to 0, and if you're saving a file and setting this field, you'll have to write it as R2004 or greater, e.g.,

``` rust
let mut drawing = Drawing::new();
drawing.header.version = AcadVersion::R2004;
// ... add the entity and set the color_24_bit field
```
